[package]
name = "near-lake-primitives"
description = "Primitives for NEAR Lake"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
anyhow.workspace = true
near-crypto.workspace = true
near-primitives.workspace = true
near-indexer-primitives.workspace = true
paste.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
