[package]
name = "near-lake-framework"
description = "Library to connect to the NEAR Lake S3 and stream the data"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-stream.workspace = true
async-trait.workspace = true
aws-config = { workspace = true, features = ["behavior-version-latest"] }
aws-credential-types.workspace = true
aws-sdk-s3.workspace = true
aws-types.workspace = true
bytes.workspace = true
derive_builder.workspace = true
futures.workspace = true
near-lake-context-derive.workspace = true
near-lake-primitives.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "sync", "time", "rt-multi-thread"] }
tokio-stream.workspace = true
tracing.workspace = true

[dev-dependencies]
# use by examples
anyhow.workspace = true
aws-smithy-types.workspace = true
# used in the doc examples
diesel = { workspace = true, features = ["postgres_backend", "postgres"] }
once_cell.workspace = true
# used by nft_indexer example
regex.workspace = true

[[example]]
name = "simple"
path = "../examples/simple.rs"

[[example]]
name = "actions"
path = "../examples/actions.rs"

[[example]]
name = "nft_indexer"
path = "../examples/nft_indexer.rs"

[[example]]
name = "with_context"
path = "../examples/with_context.rs"
