[package]
name = "near-lake-parent-transaction-cache"
description = "Ready-to-use context for the Lake Framework in Rust. It provides a cache for keeping the relation between transactions and receipts in cache."
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cached.workspace = true
derive_builder.workspace = true
near-lake-framework.workspace = true

[dev-dependencies]
anyhow.workspace = true

[[example]]
name = "with_context_parent_tx_cache"
path = "../examples/with_context_parent_tx_cache.rs"
